package EventManagementServerApp;

/**
* EventManagementServerApp/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/gursimransingh/eclipse-workspace/DistributedAssignment2/CORBA/src/corbainterface/LibrariesServer.idl
* Wednesday, 3 July, 2019 6:06:29 PM EDT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public EventManagementServerApp.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (EventManagementServerApp.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventManagementServerApp.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventManagementServerApp.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventManagementServerApp.ServerInterfaceHelper.type ();
  }

}
