package EventManagementServerApp;


/**
* EventManagementServerApp/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/gursimransingh/IdeaProjects/DistributedAssignment2/CORBA/src/corbainterface/LibrariesServer.idl
* Saturday, 6 July, 2019 5:23:54 PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
