package EventManagementServerApp;


/**
* EventManagementServerApp/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/gursimransingh/eclipse-workspace/DistributedAssignment2/CORBA/src/corbainterface/LibrariesServer.idl
* Wednesday, 3 July, 2019 6:06:29 PM EDT
*/

public interface ServerInterfaceOperations 
{
  String addEvent (String eventID, String eventType, String bookingCapacity, String managerID);
  String removeEvent (String eventID, String eventType, String managerID);
  String listEventAvailability (String eventType, String managerID);
  String bookEvent (String customerID, String eventID, String eventType, String bookingAmount);
  String getBookingSchedule (String customerID, String managerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String nonOriginCustomerBooking (String customerID);
} // interface ServerInterfaceOperations
