package EventManagementServerApp;


/**
* EventManagementServerApp/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/gursimransingh/eclipse-workspace/DistributedAssignment2/CORBA/src/corbainterface/LibrariesServer.idl
* Wednesday, 3 July, 2019 6:06:29 PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
